name: Code quality check
on:
    push:
        branches:
            - master

jobs:
    Detekt:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up JDK
              uses: actions/setup-java@v2
              with:
                  distribution: 'temurin'
                  java-version: '17'

            - name: Set up Gradle
              uses: gradle/actions/setup-gradle@v1

            - name: Grant execute permission to gradlew
              run: chmod +x gradlew

            - name: Run Detekt
              run: ./gradlew detekt

            - name: Publish Detekt reports
              uses: jwgmeligmeyling/checkstyle-github-action@master
              with:
                  path: '**/detekt.xml'
