name: Code quality check
on:
    push:
        branches:
            - main

jobs:
    Detekt:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v2
              with:
                  distribution: 'temurin'
                  java-version: '17'

            - name: Grant execute permissions to gradlew
              run: chmod +x ./gradlew

            - name: Detekt
              run: ./gradlew detekt

            - name: Publish Detekt reports
              uses: jwgmeligmeyling/checkstyle-github-action@master
              with:
                  path: '**/detekt.xml'

